# Generated by smlpkg-post-init version 2026-10-10T09:51
LIBDIR := lib/github.com/pzel/mltorrent
MLCOMP ?= polymlb
SMLPKG_PATH := -mlb-path-var "SMLPKG $(shell pwd)/lib"
MAIN_MLB=$(LIBDIR)/mltorrent.mlb

ifeq ($(MLCOMP), polymlb)
MLCOMP_FLAGS=-default-ann "ignoreFiles call-main.sml"
POLY_PATH := -mlb-path-var "POLY \$$(SML_LIB)/basis/"
else
MLCOMP_FLAGS=-default-ann "allowRecordPunExps true"
POLY_PATH := -mlb-path-var "POLY \$$(SMLPKG)/github.com/pzel/polyml-fill/"
MAIN_MLB=$(LIBDIR)/call-main.mlb
endif

COMP := $(MLCOMP) $(MLCOMP_FLAGS) $(SMLPKG_PATH) $(POLY_PATH) -output

.PHONY: all
all:	 test

.PHONY: clean
clean:
	-@rm -f bin/*

.PHONY: test
test: bin/test
	./$< --progress

.PHONY: repl
repl:
	polymlb-repl $(MAIN_MLB)

bin/test: $(shell find $(LIBDIR))
	$(COMP) $@ $(LIBDIR)/test/test.mlb

bin/mltorrent: bin $(shell find $(LIBDIR))
	$(COMP) $@ $(MAIN_MLB)


